language: c
install: bash -e .travis-ci-install.sh
script: bash -e .travis-ci.sh
cache: apt
dist: trusty
sudo: required
matrix:
  include:
  - os: linux
    env: OCAML_VERSION=4.06 OPAM_VERSION=1.2.2 INSTALL_LOCAL=1
